= Admin Guideline
Squadtopia <squadtopia@open-email.de>
0.1, 2021-01-30
:toc: left
:icons: font
:doctype: article
:docinfo: shared
:favicon:

Der Admin-Guide soll helfen ein konsistentes durchgreifen der Admins auf dem Server zu regeln um Willkür zu vermeiden.
Um dies zu erreichen sind die nachfolgenden Informationen zu berücksichtigen.

== Servervision

=== Phase 1
Ziel ist es einen Server zu schaffen, der durchgehend ein spielbares Niveau hat:

* Jeder SL kommuniziert
* Jeder SL spielt objective mit seinem Squad
* Niemand wasted Fahrzeuge/Tickets unnötig

=== Phase 2
Ziel ist es einen Server zu schaffen, der durchgehend ein experienced Niveau hat:

* Alles von Phase 1
* Insgesamt ein höheres Niveau nicht nur bezogen auf die SLs
* ...

== Grundlagen / Anforderungen

Die Admins sind in erster Linie dafür verantwortlich, dass die *bestmögliche Spielerfahrung im Rahmen der Servervision* geschaffen wird.

Deshalb sollten bei Adminentscheidungen immer folgende Punkte berücksichtigt werden:

* Trägt die Entscheidung dazu bei, dass sich die Spielqualität im Sinne der Servervision verbessert/verbessern kann.
Einen Spieler wegen einem formalen Regelverstoß zu kicken trägt eventuell nicht immer zu diesem Ziel bei.
* Wenn der Admin nicht über das nötige Wissen verfügt, um eine Situation zu beurteilen oder Unsicherheit besteht, sollte er einen anderen Admin hinzuziehen
* Admins sollen *NICHT* jede einzelne taktische Entscheidung der SLs beurteilen, sondern nur grobes Fehlverhalten bestrafen
(Superfob am Arsch der Welt, offen erkennbarer Mangel an grundlegenden Fähigkeiten etc.)
* Admin sollte öfters selbst SL spielen und mit den grundlegenden Spielmechaniken vertraut sein
* Admins sollten in der Lage sein Englisch zu reden
* Alle Admins sollten in der Lage sein, die Servervision Außenstehenden zu erläutern und den Sinn der Spielregeln zu erklären

== Regeln
include::rules.adoc[]

== Auslegung
=== Ticket-Wasting

* unnötiges Spawnen an verlorenen Objectives, usw.
* verlieren von Fahrzeugen durch fehlendes Grundlagenwissen oder das ignorieren von Informationen
* Taktisch sinnvolles Opfern von Fahrzeugen IST ERLAUBT, falls das entsprechende Ziel nicht anders erreicht werden kann, z.b. das Rammen eines vollbesetzten feindlichen Helis, der auf der nicht verteidigten Defense landen will, aggressives Pushen in Feinde um z.b. einen Hotdrop zu machen/eine Fob zu setzen. Im Zweifel muss der Verursacher erklären können, welchen taktischen Vorteil das Ticketwasting hatte.


=== Fahrzeug-Claiming

* nach dem Respawn des Fahrzeuges hat das ursprüngliche Squad Vorrecht (-> MBT Squad 1 wartet auf MBT1 respawn, MBT Squad 2 wartet auf MBT2 Respawn)
* die Regel soll nicht dazu führen, dass Fahrzeuge nicht besetzt werden können, d.h., wenn ein geclaimtes Fahrzeug nicht umgehend besetzt wird, verliert das Squad das Recht auf die Nutzung
(z.b. MBT Squad 1 im BTR auf der anderen Mapseite ist und MBT Squad 2 schon in der Main wartet, MBT Squad 1 nicht genug Leute hat usw.)

NOTE: Admins gehen davon aus, dass sich die Fahrzeugsquads untereinander abstimmen in solchen Fällen

=== Grundlegende SL-Fähigkeiten

* SLs arbeiten aktiv mit dem Team einen Plan aus und leiten relevante Informationen weiter
* SLs kennen die Bezeichnung, Fähigkeiten und Markierungen (!!!) aller relevanten Fahrzeuge, Klassen, etc.
* SLs kennen die FOB-, Rally- und Respawn-Mechaniken
* SLs kennen die Cap-Mechaniken inklusive Doppelneutral
* SLs mit weniger Erfahrung kompensieren dies durch Absprache mit den anderen SLs
* SLs sorgen dafür, dass jeder Spieler im Squad kommuniziert, sich aktiv einbringt und nur Aufgaben übernimmt, die er auch erfüllen kann
* SLs sind in der Lage die taktische Situation einzuschätzen und entsprechend zu handeln:
Neben meinem Squad erscheint eine Flagge::
-> Ich cappe und verteidige falls nötig
Mein Squad kämpft alleine ohne FOB auf der Defense gegen 2 feindliche Squads::
-> Ich rufe Hilfe etc.
* Infanterie-SLs führen ihr Squad als Infanterist, nicht als Fahrzeugbesatzung (wegen Rally, Situational Awareness usw.)


=== Fremdwerbung

* Als Fremdwerbung wird Werbung betrachtet, die unserer Squad-Community bzw. Server-Community schadet (Werbung für andere Server etc.)
* Nicknames wie SgtSnickers, .zip, Name+Twitchlink sind hingegen erlaubt

=== Namen

* Alles was einen aussprechbaren Teil im Namen hat, ist in Ordnung, z.B. B1, asdf.
* Nicht erlaubt sind 012342345509345, kyrillische usw. Zeichen
* Im Zweifelsfall an den SL delegieren

=== Sprache

Im SL-Funk ist deutsch zu sprechen.
Die Squads dürfen anderssprachig sein.

=== Free Weekend / Neulinge
 * Admins/erfahrene SLs bilden offene Squads und fangen neue Spieler auf
 * Komplette Neulingsquads: NEIN
 * Nur Neulinge in Fahrzeugen: NEIN

=== Balancing
 * Admins sind angehalten darauf zu achten, dass die Spielbalance gehalten wird
 * Auf Clans oder gute SLs der übermächtigen Seite vor Rundenende zugehen und um Balance bitten (Also Balance mit Absprache)

=== Sonstiges

* MG/HAT 1x pro squad -> nichts machen, wenn sich keiner beschwert
* 5 € in Serverkasse wer ChangeMap anstatt SetNextMap macht

== Trigger
.Aktuelle Trigger (Text weicht möglicherweise ab)
[cols="1m,2"]
|===
h|Trigger im AdminChat
h|Text

|!stream
|Streamen ist auf diesem Server untersagt!

|!tk
|Für Teamkills muss sich entschuldigt werden!

|!sl
|Squadleader haben ein SL-Kit zu verwenden!

|!seeding
| Es wird nur um die mittlere(n) Flagge(n) gekämpft!

  Das Angreifen der gegnerischen Radios & HABs ist verboten!

  Offensive Emplacements, C4, Minen, AT/RPG und bewaffnete Fahrzeuge sind während des Seedings untersagt!

  HABs müssen mindestens 150m von der Mittelflagge entfernt sein!

|!crewman
|Fahrzeuge, die Crewmankits erfordern, müssen mindestens mit 2 Mann besetzt werden!

|!locked
|Geschlossene Infantry-Squads sind erst ab dem 3. Mann erlaubt.

|!mic
|Squadleader müssen ein Mikrofon verwenden & kommunizieren!

|!main
|Das aktive Abcampen der gegnerische Main ist untersagt!

|!spezial
|HMG/HAT dürfen nur 1 mal pro Squad besetzt werden

|!dc
|Besucht uns gerne auf unserem Discord

|!help
|Wenn ihr Hilfe benötigt, wendet euch im Discord in #support an uns

|!werbung
|Fremdwerbung ist verboten!

|!info
|Auf unserer Website “www.squadtopia.de” findet ihr alle wichtigen Regeln, Infos und Links
|===

== Links

Github::
Änderungen an diesem Dokument können in unserem Github Repository vorgenommen werden: +
Link: link:https://github.com/squadtopia/[icon:github[4x]]

BattleMetrics::
Muss zur Administration verwendet werden.
Nur in Notfällen ingame Console verwenden.
Link: https://battlemetrics.com

Portainer::
Erlaubt das Neustarten von Diensten, unter anderem den Discord Bot und den Squad-Server.
Link: https://portainer.squadtopia.de (Neustarten von Server und anderen Diensten)

NOTE: Das Neustarten über Portainer geht an systemd vorbei und kann zu Problemen führen.
Sollte also nur in Notfällen benutzt werden, wenn z.B. kein SSH-Zugriff möglich ist

Grafana Dashboard::
Gibt einen Übersicht über den Zustand des Servers, wie CPU-Auslastung, Netzwerktraffic, RAM-Auslastung, usw.
Link: http://stats.labmonkeys.space/

Game Server Administration Guidelines::
Richtlinien die wir als Server erfüllen müssen, um eine Lizenz zu bekommen bzw. diese zu behalten.
Link: https://docs.google.com/document/d/13hoWNEgzz7H1eNFSzDqTQOU3UcBUOKoJjPuD9K6FL7Y/edit#heading=h.jbmnezbstl14 (englisch)
